//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopia.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopia.Dashboard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش های افزوده  شده به این اکشن.
        /// </summary>
        public static string AddedRolesToThisAction {
            get {
                return ResourceManager.GetString("AddedRolesToThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دادن پاسخ.
        /// </summary>
        public static string AnswerIt {
            get {
                return ResourceManager.GetString("AnswerIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ ها.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از انجام این کار مطمن هستید؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ها.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان آپلود بیشتر از {{maxFiles}} فایل نیست.
        /// </summary>
        public static string CannotUploadAnyMoreFiles {
            get {
                return ResourceManager.GetString("CannotUploadAnyMoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه بررسی.
        /// </summary>
        public static string CheckResult {
            get {
                return ResourceManager.GetString("CheckResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینجا کلیک کنید.
        /// </summary>
        public static string CickHere {
            get {
                return ResourceManager.GetString("CickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی آدرس.
        /// </summary>
        public static string CopyAddress {
            get {
                return ResourceManager.GetString("CopyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام حقوق مادی و معنوی این اثر محفوظ می باشد.
        /// </summary>
        public static string CopyRights {
            get {
                return ResourceManager.GetString("CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد حساب.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل خود را اینجا رها کنید.
        /// </summary>
        public static string DropYourFileHere {
            get {
                return ResourceManager.GetString("DropYourFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل های خود را اینجا رها کنید.
        /// </summary>
        public static string DropYourFilesHere {
            get {
                return ResourceManager.GetString("DropYourFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;حجم فایل ({{filesize}}) بیش از حد مجاز است ({{maxFilesize}}MB).&quot;.
        /// </summary>
        public static string DropzoneFileIsTooBig {
            get {
                return ResourceManager.GetString("DropzoneFileIsTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است، دوباره تلاش نمایید.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در پردازش درخواست خطا رخ داده است.
        /// </summary>
        public static string ErrorPageMessage {
            get {
                return ResourceManager.GetString("ErrorPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور ساز.
        /// </summary>
        public static string FactorGenerator {
            get {
                return ResourceManager.GetString("FactorGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل پشتیبانی نمی شود.
        /// </summary>
        public static string FileFormatNotSupported {
            get {
                return ResourceManager.GetString("FileFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ایمیل را درست وارد نمایید.
        /// </summary>
        public static string FillFieldCorrectly {
            get {
                return ResourceManager.GetString("FillFieldCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلترها.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور را فراموش کرده ام!.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برو به.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ را درست وارد نمایید.
        /// </summary>
        public static string IncorrectDate {
            get {
                return ResourceManager.GetString("IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ را درست وارد نمایید (ISO).
        /// </summary>
        public static string IncorrectDateISO {
            get {
                return ResourceManager.GetString("IncorrectDateISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقداری با فرمت مناسب وارد نمایید.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا آدرس اینترنتی را درست وارد نمایید.
        /// </summary>
        public static string IncorrectUrl {
            get {
                return ResourceManager.GetString("IncorrectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل صحیح نیست.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم ها.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکترها میبایست بین {0} و {1} باشد.
        /// </summary>
        public static string LenghIsNotInRange {
            get {
                return ResourceManager.GetString("LenghIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر اصلی.
        /// </summary>
        public static string MainImage {
            get {
                return ResourceManager.GetString("MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا بیشتر از {1} کاراکتر وارد ننمایید.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا بیشتر از {0} کاراکتر وارد ننمایید.
        /// </summary>
        public static string MaxLengthExeeded {
            get {
                return ResourceManager.GetString("MaxLengthExeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقداری کمتر یا مساوی با {0} وارد نمایید.
        /// </summary>
        public static string MaxValueExceeded {
            get {
                return ResourceManager.GetString("MaxValueExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل کاراکتر مجاز 5  و حداکثر {1} می باشد..
        /// </summary>
        public static string Min5MaxLength {
            get {
                return ResourceManager.GetString("Min5MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کمتر از {1} کاراکتر وارد ننمایید.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا حداقل {0} کاراکتر وارد نمایید.
        /// </summary>
        public static string MinLengthNotReached {
            get {
                return ResourceManager.GetString("MinLengthNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقداری بیشتر یا مساوی با {0} وارد نمایید.
        /// </summary>
        public static string MinValueNotReached {
            get {
                return ResourceManager.GetString("MinValueNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیدا نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مورد نظر یافت نشد!.
        /// </summary>
        public static string NotFoundPageMessage {
            get {
                return ResourceManager.GetString("NotFoundPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا حداقل یک مورد را قیمت گذاری نمایید.
        /// </summary>
        public static string PleasePriceAtleastOne {
            get {
                return ResourceManager.GetString("PleasePriceAtleastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه قبلی.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است.
        /// </summary>
        public static string ProjectDesctiption {
            get {
                return ResourceManager.GetString("ProjectDesctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر پیدا نشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید به ایمیل شما ارسال خواهد شد.
        /// </summary>
        public static string RecoverPasswordHint {
            get {
                return ResourceManager.GetString("RecoverPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد اجباری می باشد.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ها.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرشاخه.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینجا جستجو کنید.
        /// </summary>
        public static string SearchHere {
            get {
                return ResourceManager.GetString("SearchHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال جستجو ....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا انتخاب نمایید.
        /// </summary>
        public static string SelectPlease {
            get {
                return ResourceManager.GetString("SelectPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پاسخ ها.
        /// </summary>
        public static string ShowAnswers {
            get {
                return ResourceManager.GetString("ShowAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string SignInToAccount {
            get {
                return ResourceManager.GetString("SignInToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام فروشگاه.
        /// </summary>
        public static string StoreSignUp {
            get {
                return ResourceManager.GetString("StoreSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ موردی یافت نشد.
        /// </summary>
        public static string ThereIsNoRecord {
            get {
                return ResourceManager.GetString("ThereIsNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به هیچ صفحه ای دسترسی ندارید.
        /// </summary>
        public static string ThereIsNoViewForUser {
            get {
                return ResourceManager.GetString("ThereIsNoViewForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نهایی.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان دسترسی به بخش مورد نظر وجود ندارد.
        /// </summary>
        public static string UnAuthorizedPageMessage {
            get {
                return ResourceManager.GetString("UnAuthorizedPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری (ایمیل).
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران در نقش انتخابی.
        /// </summary>
        public static string UsersInThisRole {
            get {
                return ResourceManager.GetString("UsersInThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار سنجی ناموفق بود، دویاره سعی نمایید.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مقداری بین {0} و {1} وارد نمایید.
        /// </summary>
        public static string ValueIsNotInRange {
            get {
                return ResourceManager.GetString("ValueIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رقم وارد نمایید.
        /// </summary>
        public static string ValueMustBeDigit {
            get {
                return ResourceManager.GetString("ValueMustBeDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا عدد وارد نمایید.
        /// </summary>
        public static string ValueMustBeNumber {
            get {
                return ResourceManager.GetString("ValueMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا همان مقدار را دوباره وارد نمایید.
        /// </summary>
        public static string ValueNotMatched {
            get {
                return ResourceManager.GetString("ValueNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به داشبورد مدیریت شاپیا خوش آمدید.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ حسابی نداید؟.
        /// </summary>
        public static string WithoutAccountText {
            get {
                return ResourceManager.GetString("WithoutAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وروذی باید ایمیل باشد.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
