//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopia.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopia.Domain.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکشن.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اکشن.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع آدرس.
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپلیکیشن.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد خرید.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سبد خرید.
        /// </summary>
        public static string BasketId {
            get {
                return ResourceManager.GetString("BasketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیوگرافی.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بیوگرافی.
        /// </summary>
        public static string BioUrl {
            get {
                return ResourceManager.GetString("BioUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس داخلی فایل.
        /// </summary>
        public static string CdnFileUrl {
            get {
                return ResourceManager.GetString("CdnFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس داخلی فایل کوچک.
        /// </summary>
        public static string CdnThumbnailUrl {
            get {
                return ResourceManager.GetString("CdnThumbnailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نظر.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کنترلر.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مشتری.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پیگیری تحویل.
        /// </summary>
        public static string DeliverTrackingId {
            get {
                return ResourceManager.GetString("DeliverTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات تحویل.
        /// </summary>
        public static string DeliveryDetail {
            get {
                return ResourceManager.GetString("DeliveryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت پخش.
        /// </summary>
        public static string DeliveryProvider {
            get {
                return ResourceManager.GetString("DeliveryProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه های تحویل.
        /// </summary>
        public static string DeliverySpan {
            get {
                return ResourceManager.GetString("DeliverySpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تحویل.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تحویل.
        /// </summary>
        public static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تخفیف.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تخفیف.
        /// </summary>
        public static string DiscountPrice {
            get {
                return ResourceManager.GetString("DiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال شده.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند.
        /// </summary>
        public static string Extention {
            get {
                return ResourceManager.GetString("Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فایل.
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دنبال کننده.
        /// </summary>
        public static string FolowerCount {
            get {
                return ResourceManager.GetString("FolowerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دنبال شونده.
        /// </summary>
        public static string FolowingCount {
            get {
                return ResourceManager.GetString("FolowingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس استعلام.
        /// </summary>
        public static string InquiryUrl {
            get {
                return ResourceManager.GetString("InquiryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینستاگرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال است؟.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلبوم است؟.
        /// </summary>
        public static string IsAlbum {
            get {
                return ResourceManager.GetString("IsAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلاک شده؟.
        /// </summary>
        public static string IsBlocked {
            get {
                return ResourceManager.GetString("IsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تجاری است؟.
        /// </summary>
        public static string IsBusinessAccount {
            get {
                return ResourceManager.GetString("IsBusinessAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده؟.
        /// </summary>
        public static string IsConfirmed {
            get {
                return ResourceManager.GetString("IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فرض.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده؟.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفل شده است؟.
        /// </summary>
        public static string IsLock {
            get {
                return ResourceManager.GetString("IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی است؟.
        /// </summary>
        public static string IsPrivate {
            get {
                return ResourceManager.GetString("IsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعطیل رسمی است؟.
        /// </summary>
        public static string IsPublicHoliday {
            get {
                return ResourceManager.GetString("IsPublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوورد ریکاور شده است.
        /// </summary>
        public static string IsRecoveredPassword {
            get {
                return ResourceManager.GetString("IsRecoveredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده شده؟.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده؟.
        /// </summary>
        public static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین به روز رسانی.
        /// </summary>
        public static string LastCrawlTime {
            get {
                return ResourceManager.GetString("LastCrawlTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین لاگین.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد لایک.
        /// </summary>
        public static string LikeCount {
            get {
                return ResourceManager.GetString("LikeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف سفارش.
        /// </summary>
        public static string MaxOrderCount {
            get {
                return ResourceManager.GetString("MaxOrderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سقف تخفیف.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد درگاه.
        /// </summary>
        public static string MerchantId {
            get {
                return ResourceManager.GetString("MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام انگلیسی.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی.
        /// </summary>
        public static string NameFa {
            get {
                return ResourceManager.GetString("NameFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سفارش.
        /// </summary>
        public static string OrderComment {
            get {
                return ResourceManager.GetString("OrderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام سفارش.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت.
        /// </summary>
        public static string OrderPriority {
            get {
                return ResourceManager.GetString("OrderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس سفارش.
        /// </summary>
        public static string OrderUrl {
            get {
                return ResourceManager.GetString("OrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سر شاخه.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت در محل.
        /// </summary>
        public static string PayAtDestination {
            get {
                return ResourceManager.GetString("PayAtDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت.
        /// </summary>
        public static string PaymentGateway {
            get {
                return ResourceManager.GetString("PaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداختی ها.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرداخت.
        /// </summary>
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس بازگشت.
        /// </summary>
        public static string PostBackUrl {
            get {
                return ResourceManager.GetString("PostBackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل پست ها.
        /// </summary>
        public static string PostCount {
            get {
                return ResourceManager.GetString("PostCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آماده سازی.
        /// </summary>
        public static string PreparationDate {
            get {
                return ResourceManager.GetString("PreparationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آماده سازی محصول (روز).
        /// </summary>
        public static string PreparationDay {
            get {
                return ResourceManager.GetString("PreparationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی محصول.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل محصولات.
        /// </summary>
        public static string ProductCount {
            get {
                return ResourceManager.GetString("ProductCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس عکس پروفایل.
        /// </summary>
        public static string ProfilePictureUrl {
            get {
                return ResourceManager.GetString("ProfilePictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرنده.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گیرنده.
        /// </summary>
        public static string ReciverName {
            get {
                return ResourceManager.GetString("ReciverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ارسال.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت ارسال.
        /// </summary>
        public static string SendStatus {
            get {
                return ResourceManager.GetString("SendStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string Shaba {
            get {
                return ResourceManager.GetString("Shaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فروشگاه در شاپیا.
        /// </summary>
        public static string ShopiaUrl {
            get {
                return ResourceManager.GetString("ShopiaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در منو.
        /// </summary>
        public static string ShowInMenu {
            get {
                return ResourceManager.GetString("ShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فروشگاه.
        /// </summary>
        public static string StoreAddress {
            get {
                return ResourceManager.GetString("StoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فروشگاه.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فروشگاه.
        /// </summary>
        public static string StoreStatus {
            get {
                return ResourceManager.GetString("StoreStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فروشگاه.
        /// </summary>
        public static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تلگرام.
        /// </summary>
        public static string TelegramId {
            get {
                return ResourceManager.GetString("TelegramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فروشگاه در تلگرام.
        /// </summary>
        public static string TelegramUrl {
            get {
                return ResourceManager.GetString("TelegramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فایل کوچک.
        /// </summary>
        public static string ThumbnailUrl {
            get {
                return ResourceManager.GetString("ThumbnailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن دسترسی.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کل.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کل بعد از تخفیف.
        /// </summary>
        public static string TotalPriceAfterDiscount {
            get {
                return ResourceManager.GetString("TotalPriceAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تراکنش.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تلاش.
        /// </summary>
        public static string TryCount {
            get {
                return ResourceManager.GetString("TryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد یکتا.
        /// </summary>
        public static string UniqueId {
            get {
                return ResourceManager.GetString("UniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استفاده.
        /// </summary>
        public static string UsedDate {
            get {
                return ResourceManager.GetString("UsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مدرک.
        /// </summary>
        public static string UserAttachmentType {
            get {
                return ResourceManager.GetString("UserAttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مشتری.
        /// </summary>
        public static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتبر از تاریخ.
        /// </summary>
        public static string ValidFromDate {
            get {
                return ResourceManager.GetString("ValidFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی پی های معتبر (,).
        /// </summary>
        public static string ValidIp {
            get {
                return ResourceManager.GetString("ValidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتبر تا تاریخ.
        /// </summary>
        public static string ValidToDate {
            get {
                return ResourceManager.GetString("ValidToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس تایید پرداخت.
        /// </summary>
        public static string VerifyUrl {
            get {
                return ResourceManager.GetString("VerifyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دیده شدن.
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتس اپ.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس فروشگاه در واتس اپ.
        /// </summary>
        public static string WhatsAppUrl {
            get {
                return ResourceManager.GetString("WhatsAppUrl", resourceCulture);
            }
        }
    }
}
