//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopia.Service.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopia.Service.Resource.ServiceMessage", typeof(ServiceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود شده است.
        /// </summary>
        public static string AccountIsBlocked {
            get {
                return ResourceManager.GetString("AccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر هم اکنون عضو می باشد.
        /// </summary>
        public static string AlreadySignedUp {
            get {
                return ResourceManager.GetString("AlreadySignedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارتباط با درگاه پرداخت، دوباره تلاش نمایید.
        /// </summary>
        public static string CreateTransactionFailed {
            get {
                return ResourceManager.GetString("CreateTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس استعلام هزینه ارسال جوابگو نمی باشد، دوباره تلاش نمایید.
        /// </summary>
        public static string DeliveryAPIFailed {
            get {
                return ResourceManager.GetString("DeliveryAPIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد مورد نظر هم اکنون وجود دارد.
        /// </summary>
        public static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش ارسال معتبر نمی باشد.
        /// </summary>
        public static string InvalidDeliveryType {
            get {
                return ResourceManager.GetString("InvalidDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش معتبر نیست.
        /// </summary>
        public static string InvaliedTransaction {
            get {
                return ResourceManager.GetString("InvaliedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت کاربر قفل شده است.
        /// </summary>
        public static string MemberIsBlocked {
            get {
                return ResourceManager.GetString("MemberIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر یافت نشد.
        /// </summary>
        public static string RecordNotExist {
            get {
                return ResourceManager.GetString("RecordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری شما ثبت نشده است، لطفا فرایند خرید را دوباره طی نمایید.
        /// </summary>
        public static string UserInfoMissing {
            get {
                return ResourceManager.GetString("UserInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش ناموفق بود، دوباره تلاش نمایید.
        /// </summary>
        public static string VerifyTransactionFailed {
            get {
                return ResourceManager.GetString("VerifyTransactionFailed", resourceCulture);
            }
        }
    }
}
